### ISSUE TITLE
Bug Report | Media unplayable on WebKit-based browsers

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#76]
**Describe the bug**
Reddit GIFs + videos on Libreddit are unplayable.

**To reproduce**
1. Go to [this video](https://libredd.it/r/UNBGBBIIVCHIDCTIICBG/comments/l3l6uk/karen_nyberg_demonstrating_how_to_wash_long_hair/). [Another video example.](https://libredd.it/r/cats/comments/l63x4o/danger_cushions/) [GIF example.](https://libredd.it/r/gifs/comments/l673go/dogs_are_very_weird/)
2. A play button with a line through it appears

**Expected behavior**
GIFs/videos should be playable. I’m not sure why Safari on iOS isn’t able to play them on Libreddit. Those very same GIFs and videos play well on Reddit.

**Additional context**
Reproduced on all of Libreddit’s working instances.

![405634D4-A994-4AEE-AABC-8450AA0DC310](https://user-images.githubusercontent.com/52135169/106098182-9c9a7b80-6106-11eb-82ec-13a489bdfe65.jpeg)

**Comment by spikecodes** [comment]
Thanks for the bug report! Perhaps this could be because Safari disables autoplay, are you able to check your settings in Safari to make sure autoplay for video is enabled?

**Comment by Mennaruuk** [comment]
There is no way to disable autoplay for iOS Safari in the settings. I dug a bit more, and I'm seeing indications this is due to Safari not being able to play Libreddit's proxy videos for some mystifying reason. I copied the HTML code relevant to the Libreddit video and pasted it into an [HTML TryIt editor ](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic)on my iPhone:
```
<!DOCTYPE html>
<html>
<body>

<h1>Libreddit video</h1>

<video class="post_media" src="https://libredd.it/proxy/aHR0cHM6Ly92LnJlZGQuaXQva3RpMDVmdjd5MWU2MS9EQVNIXzcyMC5tcDQ=" controls="" autoplay="" loop=""></video>

</body>
</html>
```
Unfortunately, the Libreddit video didn't play. I reproduced the same results for both videos above after removing the `autoplay` attribute.

Next, I modified the code by changing the URL into that of a sample MP4 video:

```
<!DOCTYPE html>
<html>
<body>

<h1>Sample non-Libreddit video</h1>

<video class="post_media" src="https://www.w3schools.com/tags/movie.mp4" controls="" autoplay="" loop=""></video>
</body>
</html>
```
The video worked well. It properly autoplayed.



I went to [Teddit ](https://github.com/teddit-net/teddit)to see if the error would come up there too. I tested how Teddit plays videos. I'm not sure how they fetch/proxy the videos from Reddit, but from what I can see [in their code](https://github.com/teddit-net/teddit/blob/3e5d5ffaa7413a073e32e8fc8d024f1eba8163e5/inc/downloadAndSave.js), they take the Reddit video and it ends up being https://teddit.net/vids/kti05fv7y1e61.mp4. I think they use FFMPEG to combine the video and audio. But an expert has to fact check me on that. [Nitter ](https://github.com/zedeus/nitter)does something similar (for example, it proxies https://video.twimg.com/ext_tw_video/1352407390998687744/pu/pl/1024x576/ij0kZVxsY3FMevGF.m3u8 into https://nitter.net/video/52A290D02AB10/https%3A%2F%2Fvideo.twimg.com%2Fext_tw_video%2F1352407390998687744%2Fpu%2Fpl%2F1024x576%2Fij0kZVxsY3FMevGF.m3u8). Now why do these Teddit and Nitter videos play and the Libreddit ones don't!? It confused me further that Safari was able to play the googlevideo.com URLs that one can get from youtube-dl for a YouTube video, and these URLs are not only long but they don't end with any filetype name.

Other things I did include disabling [cross-site tracking protection](https://stackoverflow.com/a/62734477) and [adding `?raw=true` at the end of the video URL](https://stackoverflow.com/a/48063621), but neither worked. I also read up on [an article](https://www.knightdale-computer-repair.com/coding/html-5-video-not-playing-on-mobile-safari/) claiming that this might be Cloudflare's fault, but Libredd.it only uses Cloudflare DNS not CDN, so it remains perplexing.

I got a friend's iPad and visited the same Libreddit video; the same error (play button with a slash) appeared. I know this is a problem with Safari and not Libreddit, since this video plays on virtually every other platform. I will send a bug report to Apple and see if they can fix it, since Safari can be a hit and miss with playing videos. I've had problems with playing Mega.nz MP4 videos on iOS, so even if for possibly different reasons, mobile Safari does have some limitations when it comes to video playback compared to browsers on other platforms.
![71994EB8-C05B-4393-B69A-25902D29](https://user-images.githubusercontent.com/52135169/106226806-0a51b080-61b6-11eb-858c-f4a043003424.jpg)

**Comment by spikecodes** [comment]
Thank you for this extensive research! This information is super useful.

> I reproduced the same results for both videos above after removing the `autoplay` attribute.

When you mentioned "reproduced the same results", did you mean that both videos worked without the autoplay attribute or both failed without the autoplay attribute?

I saw [this popular answer on StackOverflow](https://stackoverflow.com/a/51432655) to a similar issue. It mentioned that adding the `playsinline` attribute fixes the issue.

I've just pushed 30c33d9 which specifies the video type and that attribute in posts. Are you able to visit [the same video from before](https://libredd.it/r/UNBGBBIIVCHIDCTIICBG/comments/l3l6uk/karen_nyberg_demonstrating_how_to_wash_long_hair/) and force refresh (clear cache + refresh) to see if it works?

**Comment by spikecodes** [comment]
I also noticed Reddit passes the `Accept-Ranges` and `Content-Length` which don't get proxied through Libreddit. Perhaps proxying those might fix the issue if this doesn't.

**Comment by Mennaruuk** [comment]
The sample MP4 video played, but the Libreddit one didn’t, regardless of whether `autoplay` is present.

Unfortunately the video still isn’t playing 🙁 I played around with the `playsinline` attribute independently, and it didn’t seem to have any effect. I found [this answer ](https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/299#issuecomment-323551078)on GitHub, but it needed an extra step of adding code to a config.xml file, but there isn’t even a config.xml file for Libreddit, and I’m not sure if this would even resolve the issue. I believe there is potential in proxying the two aforementioned headers, I pray that it will fix this issue, but lack of proxy for them isn’t affecting other browsers on other platforms. Meanwhile, I just submitted the bug report to Apple, I hope they will take a close look at this and fix it from their end.

**Comment by Mennaruuk** [comment]
Thank you for your hard work, really appreciate it dude!!!!

**Comment by spikecodes** [comment]
> The sample MP4 video played, but the Libreddit one didn’t, regardless of whether `autoplay` is present.
> 
> Unfortunately the video still isn’t playing slightly_frowning_face I played around with the `playsinline` attribute independently, and it didn’t seem to have any effect.

Darn, thanks for trying anyways. 

>  I found [this answer ](https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/299#issuecomment-323551078)on GitHub, but it needed an extra step of adding code to a config.xml file, but there isn’t even a config.xml file for Libreddit, and I’m not sure if this would even resolve the issue.

I think that suggestion is for iOS app rather than websites, especially considering it needs a `config.xml` file.

> I believe there is potential in proxying the two aforementioned headers, I pray that it will fix this issue, but lack of proxy for them isn’t affecting other browsers on other platforms.

Yeah, this seems to be a mobile Safari-specific bug. 

> Meanwhile, I just submitted the bug report to Apple, I hope they will take a close look at this and fix it from their end.

Awesome!

> Thank you for your hard work, really appreciate it dude!!!!

My pleasure! 😁

**Comment by TheCultLeader666** [comment]
This appears to happen on any IOS WebKit browser

**Comment by Mennaruuk** [comment]
> 
> 
> This appears to happen on any IOS WebKit browser

Correct, I reproduced this on Firefox and Brave for iOS. [Thanks to Apple](https://developer.apple.com/app-store/review/guidelines/), browsers "must use the appropriate WebKit framework and WebKit Javascript," so other great engines like Gecko are not allowed.

**Comment by dylanarmstrong** [comment]
I'm having this same issue on desktop Safari as well, this is version 14.0.3 on Big Sur.

**Comment by Mennaruuk** [comment]
> I'm having this same issue on desktop Safari as well, this is version 14.0.3 on Big Sur.

Hi! I'm wondering, do you face the same issue on Firefox or Chrome? It's known that Libreddit still has trouble playing audio, but you can't play video on Safari or any of the other browsers on Big Sur? If so, I'll change the title to reflect that this is more of a Safari problem.

**Comment by dylanarmstrong** [comment]
Hey @Mennaruuk, just tested and it works fine in Firefox and Chrome. In Safari I get a flash of the first frame before it goes to the play button crossed out.

**Comment by Mennaruuk** [comment]
> Hey @Mennaruuk, just tested and it works fine in Firefox and Chrome. In Safari I get a flash of the first frame before it goes to the play button crossed out.

I changed the title to better reflect that this happens across different platforms on Safari. Thanks for your help!

**Comment by TheCultLeader666** [comment]
I would suggest changing the title to reflect that this is probably an issue with the webkit engine

**Comment by Mennaruuk** [comment]
I will! Firefox and Brave for iOS have the same issue.

**Comment by spikecodes** [comment]
Which version(s) of iOS had this issues?

**Comment by Mennaruuk** [comment]
I’m currently running 14.4.1 on iPhone X. Also 14.4.1 iPadOS on my friend’s iPad experiences the same issue.

**Comment by spikecodes** [comment]
Thank you! I think I've come to [this conclusion](https://github.com/spikecodes/libreddit/issues/145#issuecomment-796485154) about the issue.

I'll have to rewrite the proxy in order to asynchronously stream media and I may not be able to do this currently with [Tide](https://github.com/http-rs/tide) but I'll keep experimenting to find out!

**Comment by spikecodes** [comment]
I have concluded that #145, #76, and #14 all stem from the method Libreddit uses to proxy content so I have unified these issues under a [single bug report](https://github.com/spikecodes/libreddit/issues/147).
